id: P005606
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:06:31.127610
source_metadata:
  id: bdr:W3PD419
  title: གཡུང་དྲུང་བོན་གྱི་ལྷ་ཚོགས་དང་དཀྱིལ་འཁོར།
  author: ''
  volumes:
    1b8d805d7a7b411b8d127aaa5555c3f9:
      image_group_id: I2PD19537
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
